package com.mygdx.tankgame;

public class SupplyDrop extends GameObject{
    private Position dropPosition;
    final String specialWeaponList[] = {"Earthquake", "Nuke", "HellFire", "Kamikaze"};
    final String powerUpList[] = {"Double Damage", "Med Kit", "Skip", "Double Fuel" };
    private boolean isPowerUp;
    private int id;

    SupplyDrop(){
        //will be generated by random
//id and power up will be set in the constructor
//constructor is called randomly with probability ⅕ on every turn
        // dropPosition = (x, MAX_HEIGHT)
    }


    public Position getDropPosition() {
        return dropPosition;
    }

    public void setDropPosition(Position dropPosition) {
        this.dropPosition = dropPosition;
    }

    public boolean isPowerUp() {
        return isPowerUp;
    }

    public void setPowerUp(boolean powerUp) {
        isPowerUp = powerUp;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
    public void dropPosition(){
        // changes dropPosition
    }
    public void onOpen(Player player){
        // activates player powerUp if powerUp, adds to WeaponList if Weapon
    }
}